### ISSUE TITLE
ModLog Checks Fail

### ISSUE THREAD

**Issue by d-reddi** [fsvreddit/automodmail#18]
When Checking modlogs for actions, lookups fail. 

## Example Code:
```
---
# Example Rule 1
body: ["removed", "deleted"]
mod_action:
    moderator_name: "dcltw"
    mod_action_type: "removelink"
    action_within: "1 day"
    action_reason: "test"
verbose_logs: true
reply: |
    Hi /u/{{author}},  
    
    Remove link
archive: true
---
# Example Rule 2
body: ["removed", "deleted"]
mod_action:
    moderator_name: "dcltw"
    mod_action_type: "removecomment"
    action_within: "1 day"
    action_reason: "AC Promoter"
verbose_logs: true
reply: |
    Hi /u/{{author}},  
    
    Remove comment
archive: true
---
```
### MOD LOG
<img width="925" alt="image" src="https://github.com/fsvreddit/automodmail/assets/165563115/ec77a1c7-21d0-4e26-9f57-2f1b9d619f5b">

### VERBOSE OUTPUT
> **u/auto-modmail** said:
>
> Modmail Automator logs
> 
> ---
> 
> Priority: 0
> 
> Rule matched: false
> 
> * Body matched successfully.
> * No matching mod log entry!

### MOD LOG
<img width="1007" alt="image" src="https://github.com/fsvreddit/automodmail/assets/165563115/ecebf351-de59-4358-a351-8f652c426dd3">

### VERBOSE OUTPUT
> **u/auto-modmail** said:
>
> Modmail Automator logs
> 
> ---
> 
> Priority: 0
> 
> Rule matched: false
> 
> * Body matched successfully.
> * No matching mod log entry!

I also tried using an exact action_reason `2: test AC` and `3: AC Promoter - Repostsleuth Bot only` which also failed.
