### ISSUE TITLE
Feature Request: Set Flair 

### ISSUE THREAD

**Issue by d-reddi** [fsvreddit/automodmail#28]
Hi there!
Thanks for all your hard work on this, this tool has made a significant impact on our efficiency in responding to modmails. 

I think the ideas in the wiki for "mod macros" is really amazing.  With using a mod macro. Is it possible to add a "set_flair" for original_author? It would allow mods to quickly provide a flair and response all in one message, similar to a toolbox macro. 

```
---
is_reply: true
body: "$$koverride"
author:
    is_moderator: true
original_author:
    override_flair: true
    set_flair: ["FLAIR TEXT", "FLAIR CSS CLASS OR FLAIR TEMPLATE ID"]
reply: "Although your karma is too low, we have reviewed your history and have given you permission to post in the sub."
archive: true
---
```

The other option might be to allow dictionary keys? 
```
---
is_reply: true
body: "$$koverride"
author:
    is_moderator: true
original_author:
    override_flair: true
    set_flair:
        flair_text: "Flair text" 
        template_id: "e1651b32-e6bd-11ed-9c26-de1616aeae13"
reply: "Although your karma is too low, we have reviewed your history and have given you permission to post in the sub."
archive: true
---
```
